### PR TITLE
Various detectives, service provider fix for 5.2

### LINKED ISSUE #1: Introduce PDF Support.

### PR DESCRIPTION
**Pull request by interjection**
Fixes #1 #3 

The project that I used for PDFs still has the same fucking bug with XREFs, but it's simple enough to fork and use the other parser if it becomes a problem.

### CODE REVIEW

**Comment by lluixhi** [comment]
This looks good -- thanks, dude.

Only one comment regarding the PSD support -- it's cool to have, but it's odd to me that we're supporting a filetype that we thumbnail, but won't be renderable in the browser -- that's all.

**Comment by interjection** [comment]
Yeah, it'll be downloadable by the user though.
It doesn't thumbnail at all, the file is simple missing at this point in https://github.com/nextchan/infinity-next/tree/master/public/static/img/filetypes
Just need to add the svg.

**Comment by lluixhi** [comment]
Out of curiousity, do you think those filetype images are Numix icons?

**Comment by interjection** [comment]
The icon theme? Doesn't look similar to generic documents of theirs from a quick peek.

**Comment by interjection** [comment]
>And shouldn't you add PSD support under isImage() instead of isDocument()?

Maybe, it's technically a document.
It doesn't really matter all that much except how it's exposed in the HTML.

@FileStorage::getThumbnailClasses()

You can change it if you want, didn't really think about it.

**Comment by lluixhi** [comment]
Hmm. It also seems to have other mimetypes:
image/vnd.adobe.photoshop
image/psd
...

I'll just leave the mime as application/psd, but handle it as an image in infinity-next

**Pull request merged**
